name: tcmb_doviz
description: TCMB (Türkiye Cumhuriyet Merkez Bankası) döviz kurları için Dart API wrapper. Güncel ve tarihsel döviz kuru verilerine kolayca erişin.
version: 0.1.0
repository: https://github.com/ibidi/tcmb-doviz

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  xml: ^6.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
